name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Dependency
      run: sudo apt-get update && sudo apt-get -y install libasound2-dev
      
    - name: Cargo Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build
      run: cargo build --release --verbose
      
    - name: Publish
      uses: softprops/action-gh-release@v3
      with:
        files: target/release/radio1_cli
      if: github.ref_type == 'tag'
